# Generated by Django 4.2.7 on 2023-12-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_users_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username1',
            new_name='username',
        ),
    ]
