# Generated by Django 4.2.7 on 2024-01-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_password_users_passw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='passw',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='usern',
            new_name='username',
        ),
    ]
