# Generated by Django 4.2.7 on 2024-01-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_passw_users_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='username1',
        ),
    ]
